#!/usr/bin/env python3

import logging
import os
import pickle
import shutil
import sys

import pyinsane.abstract as pyinsane


logger = logging.getLogger(__name__)


def get_devices(local_only):
    return pyinsane.get_devices(local_only)


COMMANDS = {
    "get_devices": get_devices,
}


def main_loop(fifo_dir, fifo_filepaths):
    global COMMANDS

    length_size = len(pickle.pack("i", 0))
    fifo_c2s = os.open(fifo_filepaths[0], os.O_RDONLY)
    fifo_s2c = os.open(fifo_filepaths[1], os.O_WRONLY)

    try:
        logger.info("Ready")

        while True:
            length = os.read(fifo_c2s, length_size)
            if length == b'':
                break
            length = pickle.unpack("i", length)[0]
            cmd = os.read(fifo_c2s, length)
            if cmd == b'':
                break
            cmd = pickle.loads(cmd)

            logger.debug("> {}".format(cmd['command']))
            f = COMMANDS[cmd['command']]
            result = f(*cmd['args'], **cmd['kwargs'])
            logger.debug("< {}".format(result))

            result = pickle.dumps(result)
            length = len(result)
            length = pickle.pack("i", length)
            os.write(fifo_s2c, length)
            os.write(fifo_s2c, result)
    finally:
        os.close(fifo_s2c)
        os.close(fifo_c2s)

    shutil.rmtree(fifo_dir)
    logger.info("Daemon stopped")


if __name__ == "__main__":
    main_loop(sys.argv[1], sys.argv[2:4])
