#!/usr/bin/env python3

import logging
import os
import pickle
import sys

import pyinsane.abstract as pyinsane


logger = logging.getLogger(__name__)


def execute(command):
    return "plop"


def main_loop(fifo_filepaths):
    length_size = len(pickle.pack("i", 0))
    fifo_s2c = os.open(fifo_filepaths[0], os.O_WRONLY)
    fifo_c2s = os.open(fifo_filepaths[1], os.O_RDONLY)

    try:
        logger.info("Ready")

        while True:
            length = os.read(fifo_c2s, length_size)
            length = pickle.unpack("i", length)[0]
            cmd = os.read(fifo_c2s, length)
            cmd = pickle.loads(cmd)

            print("> {}".format(cmd['command']))
            result = execute(cmd)
            print("< {}".format(result))

            result = pickle.dumps(result)
            length = len(result)
            length = pickle.pack("i", length)
            os.write(fifo_s2c, length)
            os.write(fifo_s2c, result)
    finally:
        os.close(fifo_s2c)
        os.close(fifo_c2s)


if __name__ == "__main__":
    main_loop(sys.argv[1:3])
